
FROM node:14 AS build-env
ADD . /app
WORKDIR /app

RUN cd app && npm install && npm run-script build

FROM gcr.io/distroless/nodejs:14
COPY --from=build-env /app /app
WORKDIR /app

EXPOSE 5000

CMD ["npm", "run-script", "serve"]