name: OWASP ZAP Baseline Scan
on: [push, pull_request]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:     
    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: "https://threatdragon.github.io/"
